version: '3.9'
name: mkadia-platform
services:
  postgres:
    image: 'postgres:latest'
    container_name: mkadia-api-postgres
    environment:
      - 'POSTGRES_DB=mkadia-db'
      - 'POSTGRES_PASSWORD=soufianch'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - mkadia-api-postgres-data:/var/lib/postgresql/data
    networks:
      - mkadia-api-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: mkadia-api-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: soufianch
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    networks:
      - mkadia-api-net

  minio:
    image: minio/minio:latest
    container_name: mkadia-api-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mkadia-objects
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - mkadia-api-minio-data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - mkadia-api-net

volumes:
  mkadia-api-postgres-data:
  mkadia-api-minio-data:

networks:
  mkadia-api-net:
    name: mkadia-api-net
