name: mkadia-platform
services:
  postgres:
    image: 'postgres:latest'
    container_name: mkadia-postgres
    environment:
      - 'POSTGRES_DB=mkadia-db'
      - 'POSTGRES_PASSWORD=soufianch'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    volumes:
      - mkadia-postgres-data:/var/lib/postgresql
    networks:
      - mkadia-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: mkadia-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: soufianch
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - '5050:5050'
    networks:
      - mkadia-net

  minio:
    image: minio/minio:latest
    container_name: mkadia-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mkadia-objects
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - mkadia-minio-data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - mkadia-net

  mc:
    image: minio/mc:latest
    container_name: mkadia-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5 &&
        mc alias set mk http://minio:9000 minioadmin minioadmin &&
        mc mb mk/mkadia-media || true &&
        mc mb mk/mkadia-data || true &&
        tail -f /dev/null
      "
    networks:
      - mkadia-net

volumes:
  mkadia-postgres-data:
  mkadia-minio-data:

networks:
  mkadia-net:
    name: mkadia-net
