server:
  port: 8080
  servlet:
    context-path: /mkadia-api
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    url: jdbc:postgresql://localhost:5432/mkadia-db
    username: postgres
    password: soufianch
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: soufianch
    baseline-description: "init migration"
    baseline-version: 0
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: schajjaoui@gmail.com
    password: ekwm vcok zytr iinu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          auth: true
        debug: true
logging:
  level:
    org:
      springframework:
        security: DEBUG # or trace
# SMS Gateway
twilio:
  account:
    sid: AC3737a04a833c08f487ed1a6f891a4cff
  auth:
    token: 9fe0f5a7bd5635da621d45dcd8c316a1
  phone:
    number: +12513158452
  service:
    friendly_name: Mkadia-2F
    ssid: VA1483888b36abf62836ae4f21ccac3697

# elements of Security
jwt:
  secret: a7f4e2b1c8d5a3e1b6e8c4a5b6d8a3f5e1c6b4d8f5e1c3a7b1d878h7787e5g7u
  expiration: 3600000 # 1 hour
  refresh-token:
    expiration: 28800000 # 8 hours
  reset-token:
    expiration: 1800000
app:
  clients:
    ips:
      - name: web-client
        ip: http://localhost:4200
      - name: mobile-client
        ip: http://localhost:5000
file:
  upload-dir: D:\\Projets-Prof\\mkadia\\mkadia-app-files
  allowed:
    extensions:
      -jpg
      -png
      -svg
      -jpeg