server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /mkadia-api
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    database: 0

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: mkadia-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
  docker:
    compose:
      lifecycle-management: start_and_stop
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://postgres:5432/mkadia-db?createDatabaseIfNotExist=true
    username: postgres
    password: soufianch
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: postgres
    password: soufianch
    baseline-description: "init migration"
    baseline-version: 0
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: schajjaoui@gmail.com
    password: ekwm vcok zytr iinu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
          auth: true
          mime:
            charset: UTF-8
            encodefilename: false
        debug: true
logging:
  level:
    fr.mkadia.mkadiaapi.services.product: INFO
    fr.mkadia.mkadiaapi: INFO
    com.fasterxml.jackson: DEBUG
    org.thymeleaf: DEBUG
    fr.mkadia: DEBUG
    web: DEBUG
    org:
      springframework:
        security: DEBUG # or trace

# SMS Gateway
twilio:
  account:
    sid: AC3737a04a833c08f487ed1a6f891a4cff
  auth:
    token: 9fe0f5a7bd5635da621d45dcd8c316a1
  phone:
    number: +12513158452
  service:
    friendly_name: Mkadia-2F
    ssid: VA1483888b36abf62836ae4f21ccac3697

# elements of Security
jwt:
  secret: a7f4e2b1c8d5a3e1b6e8c4a5b6d8a3f5e1c6b4d8f5e1c3a7b1d878h7787e5g7u
  expiration: 7200000 # 1 hour
  refresh-token:
    expiration: 31557600000 # 8 hours
  reset-token:
    expiration: 1800000
app:
  clients:
    web:
      reset-url: http://localhost:4200/auth/reset/change-password
    mobile:
      deep-link: mkadia://change-password
      fallback-url: http://192.168.1.130:8080/mkadia-api/api/v1/auth/reset-password-mobile
      scheme: mkadia
      android-package: com.mkadia.app
      android-store-url: https://play.google.com/store/apps/details?id=com.mkadia.app
      ios-store-url: https://apps.apple.com/app/mkadia/id123456789
    ips:
      - name: web-client
        ip: http://localhost:4200
#      - name: mobile-client
#        ip: http://localhost:5000
minio:
    allowed-extensions: [jpg, png, pdf, txt]
    access-key: minioadmin
    secret-key: minioadmin
    url: http://localhost:9000
    bucket:
      name: mkadia-objects
    put-object-part-size: 5242880 #value in bytes (minimum is 5 MB equivalent)